### PR TITLE
Removed probably unused syscall

### PR DESCRIPTION
**Pull request by diekmann**

### CODE REVIEW

**Comment by diekmann** [comment]
I'm not happy yet

**Comment by diekmann** [comment]
I hope github will incorporate the new commit

**Comment by diekmann** [comment]
In my tool, I need the ioctl syscall; the unit tests are fine without them (on my machine). Therefore, I just added it as a comment.

I'm adding more comments and TODOs than actual lines of code ;-)

**Comment by teh** [comment]
Thanks :)

**Pull request merged**
